---
site:
  title: "Metronome"
  url: https://philips-software.github.io/amp-embedded-infra-lib/
  start_page: embedded_infrastructure_library::index.adoc
content:
  sources:
    - url: .
      start_path: EmbeddedInfraLib/documents
      branches:
        - master
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./EmbeddedInfraLib/documents/supplemental-ui
asciidoc:
  attributes:
    plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
    - asciidoctor-plantuml
