---
name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release_please:
    name: Create Release
    runs-on: windows-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@8016a6649226f2ec88ed05441c11bb5410a22d29 # v3.7.10
        id: release
        with:
          command: manifest
          token: ${{ secrets.AUTOMATIC_RELEASE_TOKEN }}
  build_upload_packages:
    name: Build & Upload Packages
    needs: release_please
    if: ${{ needs.release_please.outputs.releases_created }}
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          persist-credentials: false
      - uses: hendrikmuhs/ccache-action@fba817f3c0db4f854d7a3ee688241d6754da166e # v1.2.8
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          variant: sccache
      #- uses: lukka/run-cmake@71d20a810daaf5340669b8cce5c9fe583780e147
      #  with:
      #    configurePreset: "Package"
      #    buildPreset: "Package"
      #    configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=sccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=sccache']"
      #- run: gh release upload ${{ needs.release_please.outputs.tag_name }} Build/**/emil-*.zip --clobber
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
